# http://r-pkgs.had.co.nz/check.html
# http://docs.travis-ci.com/user/languages/r/
language: r
sudo: true

addons:
  apt:
    sources:
      - r-packages-precise
    packages:
      - r-base-dev
      - r-recommended
      - RUnit

r_github_packages:
  - jimhester/covr

env:
  global:
    - TEST_RFINTOOLS=TRUE
    - R_LIBS_USER=~/R/library

cache:
  directories:
    $R_LIBS_USER

before_script:
  - mkdir -p "$R_LIBS_USER"
  - Rscript -e 'if (length(find.package("devtools", quiet = TRUE)) == 0L) { install.packages("devtools", repos = "http://cran.rstudio.com") }'
  - Rscript -e 'devtools::update_packages("devtools", repos = "http://cran.rstudio.com")'
  - Rscript -e 'devtools::install_deps(repos = "http://cran.rstudio.com", dependencies = TRUE)'                     
  - Rscript -e 'install.packages("PerformanceAnalytics", repos = "http://cran.r-project.org", dependencies = TRUE)'
  - Rscript -e 'install.packages("PortfolioAnalytics", repos = "http://cran.r-project.org", dependencies = TRUE)'
  - Rscript -e 'install.packages("FinancialInstrument", repos = "http://r-forge.r-project.org", dependencies = TRUE)'
  - Rscript -e 'install.packages("blotter", repos = "http://r-forge.r-project.org", dependencies = TRUE)'
  - Rscript -e 'install.packages("quantstrat", repos = "http://r-forge.r-project.org", dependencies = TRUE)'
  - Rscript -e 'install.packages("covr", repos="http://cran.rstudio.com")'

script:
  - Rscript -e 'devtools::check()'

after_success:
  - Rscript -e 'library(rfintools)'
  - Rscript -e 'library(covr);codecov()'
  #covr::codecov()'
