# http://r-pkgs.had.co.nz/check.html
# http://docs.travis-ci.com/user/languages/r/
language: r
sudo: required

env:
  global:
    - TEST_RFINTOOLS=TRUE
    - R_LIBS_USER=~/R/library

before_script:
  - mkdir -p "$R_LIBS_USER"
  - Rscript -e 'if (length(find.package("devtools", quiet = TRUE)) == 0L) { install.packages("devtools", repos = "http://cran.rstudio.com") }'
  - Rscript -e 'devtools::update_packages("devtools", repos = "http://cran.rstudio.com")'
  - Rscript -e 'devtools::install_deps(repos = "http://cran.rstudio.com", dependencies = TRUE)'                     
  - Rscript -e 'install.packages("PerformanceAnalytics", repos = "http://cran.rstudio.com", dependencies = TRUE)'
  - Rscript -e 'install.packages("PortfolioAnalytics", repos = "http://cran.rstudio.com", dependencies = TRUE)'
  - Rscript -e 'install.packages("FinancialInstrument", repos="http://R-Forge.R-project.org", dependencies = TRUE)'
  - Rscript -e 'install.packages("blotter", repos="http://R-Forge.R-project.org", dependencies = TRUE)'
  - Rscript -e 'install.packages("quantstrat", repos="http://R-Forge.R-project.org", dependencies = TRUE)'
  - Rscript -e 'install.packages("covr", repos="http://cran.rstudio.com")'

script:
  - Rscript -e 'devtools::check()'

#after_success:
#  - Rscript -e 'library(rfintools)'
#  - Rscript -e 'library(covr);codecov()'
# covr::codecov()'
