# http://r-pkgs.had.co.nz/check.html
# http://docs.travis-ci.com/user/languages/r/
# Sample .travis.yml for R projects

language: r
#warnings_are_errors: true
sudo: required

r_packages:
  - PerformanceAnalytics

#install:     
r_github_packages:
  - cloudcello/blotter
  - cloudcello/quantstrat
  
before_script:   
  - Rscript -e 'install.packages("covr", repos="http://cran.rstudio.com")'
#  - Rscript -e 'install.packages(c("blotter", "quantstrat"), repos= "http://r-forge.r-project.org")'

after_success:
  - Rscript -e 'library(covr);codecov()'  
#  - Rscript -e 'library(rfintools)'
